name = "Gaycraft Pack"
author = "Octal"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75c82e93f012a5a3b6e26be7d57b040eb649959e54bb722c7b97354ccca5e988"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.21"
